-- Create recipe corpus tables: recipe_documents, parent/child chunks, sync runs, user preferences
-- and add "recipe" to conversations.source_scope check

-- Ensure vector extension available for embeddings
CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;

-- recipe_documents
CREATE TABLE public.recipe_documents (
    id bigint NOT NULL,
    source_path text NOT NULL,
    kind varchar(16) NOT NULL,
    category varchar(64) NOT NULL,
    title varchar(255) NOT NULL,
    summary text,
    ingredients text[] DEFAULT ARRAY[]::text[],
    dietary_terms text[] DEFAULT ARRAY[]::text[],
    difficulty varchar(16),
    calories_text varchar(64),
    content_markdown text NOT NULL,
    content_sha256 char(64) NOT NULL,
    source_revision varchar(64),
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL
);

ALTER TABLE public.recipe_documents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE public.recipe_documents ADD CONSTRAINT recipe_documents_pkey PRIMARY KEY (id);
CREATE UNIQUE INDEX recipe_documents_source_path_idx ON public.recipe_documents (source_path);
CREATE INDEX recipe_documents_kind_active_idx ON public.recipe_documents (kind, is_active, category);
CREATE INDEX recipe_documents_ingredients_gin ON public.recipe_documents USING GIN (ingredients);
CREATE INDEX recipe_documents_dietary_gin ON public.recipe_documents USING GIN (dietary_terms);

-- recipe_parent_chunks (metadata for chunks)
CREATE TABLE public.recipe_parent_chunks (
    id bigint NOT NULL,
    document_id bigint NOT NULL,
    parent_index integer NOT NULL,
    heading_path text,
    content text NOT NULL,
    token_count integer DEFAULT 0 NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL
);
ALTER TABLE public.recipe_parent_chunks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE public.recipe_parent_chunks ADD CONSTRAINT recipe_parent_chunks_pkey PRIMARY KEY (id);
ALTER TABLE public.recipe_parent_chunks
    ADD CONSTRAINT recipe_parent_chunks_document_fk
        FOREIGN KEY (document_id) REFERENCES public.recipe_documents(id) ON DELETE CASCADE;
CREATE INDEX recipe_parent_chunks_document_idx ON public.recipe_parent_chunks (document_id);

-- recipe_child_chunks (searchable blocks with embedding)
CREATE TABLE public.recipe_child_chunks (
    id bigint NOT NULL,
    document_id bigint NOT NULL,
    parent_id bigint NOT NULL,
    index_version integer NOT NULL,
    child_index integer NOT NULL,
    heading_path text,
    content text NOT NULL,
    embedding_text text NOT NULL,
    content_hash char(64) NOT NULL,
    search_vector tsvector NOT NULL,
    embedding public.vector(512),
    embedding_model character varying(120),
    token_count integer DEFAULT 0 NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT recipe_child_chunks_child_index_check CHECK ((child_index >= 0)),
    CONSTRAINT recipe_child_chunks_index_version_check CHECK ((index_version > 0))
);
ALTER TABLE public.recipe_child_chunks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE public.recipe_child_chunks ADD CONSTRAINT recipe_child_chunks_pkey PRIMARY KEY (id);
ALTER TABLE public.recipe_child_chunks
    ADD CONSTRAINT recipe_child_chunks_document_fk
        FOREIGN KEY (document_id) REFERENCES public.recipe_documents(id) ON DELETE CASCADE,
    ADD CONSTRAINT recipe_child_chunks_parent_fk
        FOREIGN KEY (parent_id) REFERENCES public.recipe_parent_chunks(id) ON DELETE CASCADE,
    ADD CONSTRAINT recipe_child_chunks_content_unique
        UNIQUE (document_id, index_version, content_hash);
CREATE INDEX recipe_child_chunks_document_idx ON public.recipe_child_chunks (document_id, index_version, child_index);
CREATE INDEX ix_recipe_child_chunks_search ON public.recipe_child_chunks USING gin (search_vector);

-- vector index for fast approximate nearest neighbors (ivfflat)
-- adjust lists parameter based on expected corpus size (100 is a reasonable default)
CREATE INDEX IF NOT EXISTS ix_recipe_child_chunks_embedding ON public.recipe_child_chunks USING ivfflat (embedding vector_l2_ops) WITH (lists = 100);

-- recipe_sync_runs
CREATE TABLE public.recipe_sync_runs (
    id bigint NOT NULL,
    source_revision varchar(64),
    status varchar(16) NOT NULL,
    scanned_count integer DEFAULT 0 NOT NULL,
    created_count integer DEFAULT 0 NOT NULL,
    updated_count integer DEFAULT 0 NOT NULL,
    deactivated_count integer DEFAULT 0 NOT NULL,
    failed_count integer DEFAULT 0 NOT NULL,
    started_at timestamptz DEFAULT now() NOT NULL,
    finished_at timestamptz
);
ALTER TABLE public.recipe_sync_runs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE public.recipe_sync_runs ADD CONSTRAINT recipe_sync_runs_pkey PRIMARY KEY (id);

-- user_preferences
CREATE TABLE public.user_preferences (
    tenant_id uuid NOT NULL,
    user_id integer NOT NULL,
    dietary_restrictions text[] DEFAULT ARRAY[]::text[],
    timezone varchar(64),
    version integer DEFAULT 1 NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT user_preferences_unique UNIQUE (tenant_id, user_id),
    CONSTRAINT user_preferences_tenant_user_fk
        FOREIGN KEY (tenant_id, user_id) REFERENCES public.tenants(id, user_id) ON DELETE CASCADE
);

-- add recipe to conversations source_scope check
ALTER TABLE public.conversations DROP CONSTRAINT IF EXISTS conversations_source_scope_check;
ALTER TABLE public.conversations
    ADD CONSTRAINT conversations_source_scope_check CHECK ((source_scope::text = ANY ((ARRAY['knowledge'::character varying, 'growth'::character varying, 'all'::character varying, 'recipe'::character varying])::text[])));

-- Grants: allow read access to diary_app role where appropriate
GRANT SELECT ON public.recipe_documents TO diary_app;
GRANT SELECT ON public.recipe_parent_chunks TO diary_app;
GRANT SELECT ON public.recipe_child_chunks TO diary_app;
GRANT SELECT ON public.recipe_sync_runs TO diary_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_preferences TO diary_app;

-- recipe_message_sources: links messages to recipe documents (minimal)
CREATE TABLE public.recipe_message_sources (
    id bigint NOT NULL,
    tenant_id uuid NOT NULL,
    message_id integer NOT NULL,
    document_id bigint NOT NULL,
    snippet text,
    rank integer NOT NULL,
    source_deleted boolean DEFAULT false NOT NULL
);
ALTER TABLE public.recipe_message_sources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE public.recipe_message_sources ADD CONSTRAINT recipe_message_sources_pkey PRIMARY KEY (id);
ALTER TABLE public.recipe_message_sources
    ADD CONSTRAINT recipe_message_sources_message_fk
        FOREIGN KEY (message_id) REFERENCES public.messages(id) ON DELETE CASCADE,
    ADD CONSTRAINT recipe_message_sources_document_fk
        FOREIGN KEY (document_id) REFERENCES public.recipe_documents(id);
CREATE INDEX recipe_message_sources_lookup_idx
    ON public.recipe_message_sources (tenant_id, message_id, rank);

ALTER TABLE public.user_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recipe_message_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_preferences FORCE ROW LEVEL SECURITY;
ALTER TABLE public.recipe_message_sources FORCE ROW LEVEL SECURITY;
CREATE POLICY user_preferences_tenant_isolation ON public.user_preferences
    USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true),'')::uuid)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant_id', true),'')::uuid);
CREATE POLICY recipe_message_sources_tenant_isolation ON public.recipe_message_sources
    USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true),'')::uuid)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant_id', true),'')::uuid);

GRANT SELECT, INSERT ON public.recipe_message_sources TO diary_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO diary_app;
