ALTER TABLE public.attachments ADD COLUMN storage_backend varchar(16) NOT NULL DEFAULT 'local', ADD COLUMN object_key text, ADD COLUMN object_version text, ADD COLUMN etag text, ADD COLUMN deleted_at timestamptz;
ALTER TABLE public.attachments ADD CONSTRAINT attachments_storage_backend_check CHECK (storage_backend IN ('local','minio')), ADD CONSTRAINT attachments_object_key_safe CHECK (object_key IS NULL OR object_key !~ '(^[/\\]|(^|[/\\])\.\.([/\\]|$)|^[A-Za-z]:)');
CREATE UNIQUE INDEX ux_attachments_object_key ON public.attachments(object_key) WHERE object_key IS NOT NULL;
ALTER TABLE public.knowledge_documents ADD COLUMN storage_backend varchar(16) NOT NULL DEFAULT 'local', ADD COLUMN object_key text, ADD COLUMN object_version text, ADD COLUMN etag text;
ALTER TABLE public.knowledge_assets ADD COLUMN storage_backend varchar(16) NOT NULL DEFAULT 'local', ADD COLUMN object_key text, ADD COLUMN object_version text, ADD COLUMN etag text;
CREATE TABLE public.object_gc_jobs(id bigserial PRIMARY KEY,tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,storage_backend varchar(16) NOT NULL,object_key text NOT NULL,object_version text,available_at timestamptz NOT NULL DEFAULT now(),attempt_count integer NOT NULL DEFAULT 0,status varchar(16) NOT NULL DEFAULT 'queued',last_error_code varchar(80),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(storage_backend,object_key,object_version));
ALTER TABLE public.object_gc_jobs ENABLE ROW LEVEL SECURITY; ALTER TABLE public.object_gc_jobs FORCE ROW LEVEL SECURITY;
CREATE POLICY object_gc_jobs_tenant_isolation ON public.object_gc_jobs USING (tenant_id=NULLIF(current_setting('app.current_tenant_id',true),'')::uuid) WITH CHECK (tenant_id=NULLIF(current_setting('app.current_tenant_id',true),'')::uuid);
GRANT SELECT,INSERT,UPDATE,DELETE ON public.object_gc_jobs TO cortex_app; GRANT USAGE,SELECT ON SEQUENCE public.object_gc_jobs_id_seq TO cortex_app;
