-- Restore legacy recipe tables in their final pre-removal state (after
-- 000010 recipe_corpus, 000011 recipe_index_jobs and 000016 recipe_retrieval_v2).
-- This is only used to roll back 000018_drop_recipe_tables; the tables are
-- recreated empty.

CREATE TABLE public.recipe_documents (
    id bigint NOT NULL,
    source_path text NOT NULL,
    kind varchar(16) NOT NULL,
    category varchar(64) NOT NULL,
    title varchar(255) NOT NULL,
    summary text,
    ingredients text[] DEFAULT ARRAY[]::text[],
    dietary_terms text[] DEFAULT ARRAY[]::text[],
    difficulty varchar(16),
    calories_text varchar(64),
    content_markdown text NOT NULL,
    content_sha256 char(64) NOT NULL,
    source_revision varchar(64),
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    active_index_version integer NOT NULL DEFAULT 1,
    CONSTRAINT recipe_documents_active_index_version_check CHECK (active_index_version > 0)
);
ALTER TABLE public.recipe_documents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE public.recipe_documents ADD CONSTRAINT recipe_documents_pkey PRIMARY KEY (id);
CREATE UNIQUE INDEX recipe_documents_source_path_idx ON public.recipe_documents (source_path);
CREATE INDEX recipe_documents_kind_active_idx ON public.recipe_documents (kind, is_active, category);
CREATE INDEX recipe_documents_ingredients_gin ON public.recipe_documents USING GIN (ingredients);
CREATE INDEX recipe_documents_dietary_gin ON public.recipe_documents USING GIN (dietary_terms);

CREATE TABLE public.recipe_parent_chunks (
    id bigint NOT NULL,
    document_id bigint NOT NULL,
    parent_index integer NOT NULL,
    heading_path text,
    content text NOT NULL,
    token_count integer DEFAULT 0 NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    index_version integer NOT NULL DEFAULT 1,
    CONSTRAINT recipe_parent_chunks_index_version_check CHECK (index_version > 0)
);
ALTER TABLE public.recipe_parent_chunks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE public.recipe_parent_chunks ADD CONSTRAINT recipe_parent_chunks_pkey PRIMARY KEY (id);
ALTER TABLE public.recipe_parent_chunks
    ADD CONSTRAINT recipe_parent_chunks_document_fk
        FOREIGN KEY (document_id) REFERENCES public.recipe_documents(id) ON DELETE CASCADE;
CREATE INDEX recipe_parent_chunks_document_idx
    ON public.recipe_parent_chunks (document_id, index_version, parent_index);

CREATE TABLE public.recipe_child_chunks (
    id bigint NOT NULL,
    document_id bigint NOT NULL,
    parent_id bigint NOT NULL,
    index_version integer NOT NULL,
    child_index integer NOT NULL,
    heading_path text,
    content text NOT NULL,
    embedding_text text NOT NULL,
    content_hash char(64) NOT NULL,
    search_vector tsvector NOT NULL,
    embedding public.vector(512),
    embedding_model character varying(120),
    token_count integer DEFAULT 0 NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT recipe_child_chunks_child_index_check CHECK ((child_index >= 0)),
    CONSTRAINT recipe_child_chunks_index_version_check CHECK ((index_version > 0))
);
ALTER TABLE public.recipe_child_chunks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE public.recipe_child_chunks ADD CONSTRAINT recipe_child_chunks_pkey PRIMARY KEY (id);
ALTER TABLE public.recipe_child_chunks
    ADD CONSTRAINT recipe_child_chunks_document_fk
        FOREIGN KEY (document_id) REFERENCES public.recipe_documents(id) ON DELETE CASCADE,
    ADD CONSTRAINT recipe_child_chunks_parent_fk
        FOREIGN KEY (parent_id) REFERENCES public.recipe_parent_chunks(id) ON DELETE CASCADE,
    ADD CONSTRAINT recipe_child_chunks_content_unique
        UNIQUE (document_id, index_version, content_hash);
CREATE INDEX recipe_child_chunks_document_idx
    ON public.recipe_child_chunks (document_id, index_version, child_index);
CREATE INDEX ix_recipe_child_chunks_search ON public.recipe_child_chunks USING gin (search_vector);
CREATE INDEX ix_recipe_child_chunks_embedding
    ON public.recipe_child_chunks USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);

CREATE TABLE public.recipe_index_jobs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id bigint NOT NULL,
    target_index_version integer NOT NULL CHECK (target_index_version > 0),
    status varchar(20) NOT NULL DEFAULT 'queued'
        CHECK (status IN ('queued', 'running', 'success', 'failed', 'cancelled')),
    lease_owner varchar(120),
    lease_until timestamptz,
    attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    next_attempt_at timestamptz NOT NULL DEFAULT now(),
    last_error_code varchar(80),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT recipe_index_jobs_document_fk
        FOREIGN KEY (document_id) REFERENCES public.recipe_documents(id) ON DELETE CASCADE,
    CONSTRAINT recipe_index_jobs_document_version_unique
        UNIQUE (document_id, target_index_version)
);
CREATE INDEX ix_recipe_index_jobs_claim
    ON public.recipe_index_jobs (status, next_attempt_at, lease_until, id)
    WHERE status IN ('queued', 'running');
CREATE INDEX ix_recipe_index_jobs_document
    ON public.recipe_index_jobs (document_id, updated_at DESC);

CREATE TABLE public.recipe_message_sources (
    id bigint NOT NULL,
    tenant_id uuid NOT NULL,
    message_id integer NOT NULL,
    document_id bigint NOT NULL,
    snippet text,
    rank integer NOT NULL,
    source_deleted boolean DEFAULT false NOT NULL
);
ALTER TABLE public.recipe_message_sources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE public.recipe_message_sources ADD CONSTRAINT recipe_message_sources_pkey PRIMARY KEY (id);
ALTER TABLE public.recipe_message_sources
    ADD CONSTRAINT recipe_message_sources_message_fk
        FOREIGN KEY (message_id) REFERENCES public.messages(id) ON DELETE CASCADE,
    ADD CONSTRAINT recipe_message_sources_document_fk
        FOREIGN KEY (document_id) REFERENCES public.recipe_documents(id);
CREATE INDEX recipe_message_sources_lookup_idx
    ON public.recipe_message_sources (tenant_id, message_id, rank);
ALTER TABLE public.recipe_message_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recipe_message_sources FORCE ROW LEVEL SECURITY;
CREATE POLICY recipe_message_sources_tenant_isolation ON public.recipe_message_sources
    USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true),'')::uuid)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant_id', true),'')::uuid);

CREATE TABLE public.recipe_sync_runs (
    id bigint NOT NULL,
    source_revision varchar(64),
    status varchar(16) NOT NULL,
    scanned_count integer DEFAULT 0 NOT NULL,
    created_count integer DEFAULT 0 NOT NULL,
    updated_count integer DEFAULT 0 NOT NULL,
    deactivated_count integer DEFAULT 0 NOT NULL,
    failed_count integer DEFAULT 0 NOT NULL,
    started_at timestamptz DEFAULT now() NOT NULL,
    finished_at timestamptz
);
ALTER TABLE public.recipe_sync_runs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE public.recipe_sync_runs ADD CONSTRAINT recipe_sync_runs_pkey PRIMARY KEY (id);

GRANT SELECT ON public.recipe_documents TO diary_app;
GRANT SELECT ON public.recipe_parent_chunks TO diary_app;
GRANT SELECT ON public.recipe_child_chunks TO diary_app;
GRANT SELECT ON public.recipe_sync_runs TO diary_app;
GRANT SELECT, INSERT ON public.recipe_message_sources TO diary_app;
GRANT SELECT, USAGE ON SEQUENCE public.recipe_documents_id_seq TO diary_app;
GRANT SELECT, USAGE ON SEQUENCE public.recipe_parent_chunks_id_seq TO diary_app;
GRANT SELECT, USAGE ON SEQUENCE public.recipe_child_chunks_id_seq TO diary_app;
GRANT SELECT, USAGE ON SEQUENCE public.recipe_index_jobs_id_seq TO diary_app;
GRANT SELECT, USAGE ON SEQUENCE public.recipe_message_sources_id_seq TO diary_app;
GRANT SELECT, USAGE ON SEQUENCE public.recipe_sync_runs_id_seq TO diary_app;
