ALTER TABLE public.user_preferences ADD COLUMN marketplace_personalization boolean NOT NULL DEFAULT true;

CREATE TABLE public.public_profiles (
    tenant_id uuid PRIMARY KEY REFERENCES public.tenants(id) ON DELETE CASCADE,
    user_id integer NOT NULL UNIQUE REFERENCES public.users(id) ON DELETE CASCADE,
    public_id uuid NOT NULL UNIQUE,
    nickname varchar(40) NOT NULL CHECK (char_length(nickname) BETWEEN 2 AND 40),
    discoverable boolean NOT NULL DEFAULT false,
    version integer NOT NULL DEFAULT 1 CHECK (version > 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.writing_templates (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    created_by integer NOT NULL REFERENCES public.users(id),
    title varchar(120) NOT NULL,
    description varchar(500) NOT NULL DEFAULT '',
    content_markdown text NOT NULL CHECK (octet_length(content_markdown) BETWEEN 1 AND 65536),
    category varchar(40) NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'private' CHECK (status IN ('private','published','withdrawn')),
    version integer NOT NULL DEFAULT 1 CHECK (version > 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    UNIQUE (tenant_id, id)
);

CREATE TABLE public.template_publications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id uuid NOT NULL,
    template_id bigint NOT NULL,
    template_version integer NOT NULL,
    title varchar(120) NOT NULL,
    description varchar(500) NOT NULL,
    content_markdown text NOT NULL,
    category varchar(40) NOT NULL,
    content_sha256 char(64) NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'published' CHECK (status IN ('published','withdrawn')),
    published_at timestamptz NOT NULL DEFAULT now(),
    withdrawn_at timestamptz,
    UNIQUE (tenant_id, template_id, template_version),
    FOREIGN KEY (tenant_id, template_id) REFERENCES public.writing_templates(tenant_id, id)
);

CREATE TABLE public.published_template_snapshots (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_template_id uuid NOT NULL,
    source_publication_id bigint NOT NULL UNIQUE REFERENCES public.template_publications(id),
    author_public_id uuid NOT NULL REFERENCES public.public_profiles(public_id),
    author_nickname varchar(40) NOT NULL,
    version integer NOT NULL,
    title varchar(120) NOT NULL,
    description varchar(500) NOT NULL,
    content_markdown text NOT NULL,
    category varchar(40) NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'published' CHECK (status IN ('published','withdrawn')),
    published_at timestamptz NOT NULL DEFAULT now(),
    withdrawn_at timestamptz,
    UNIQUE (public_template_id, version)
);
CREATE UNIQUE INDEX uq_published_template_active ON public.published_template_snapshots(public_template_id) WHERE status='published';
CREATE INDEX ix_published_template_list ON public.published_template_snapshots(status, published_at DESC, id DESC);

CREATE TABLE public.template_reactions (
    tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    user_id integer NOT NULL REFERENCES public.users(id),
    public_template_id uuid NOT NULL,
    kind varchar(20) NOT NULL CHECK (kind IN ('like','favorite')),
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, user_id, public_template_id, kind)
);

CREATE TABLE public.template_usages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    user_id integer NOT NULL REFERENCES public.users(id),
    public_template_id uuid,
    source_template_id bigint,
    snapshot_version integer NOT NULL,
    note_id integer NOT NULL REFERENCES public.notes(id),
    idempotency_key varchar(128) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, idempotency_key),
    UNIQUE (tenant_id, note_id)
);

CREATE TABLE public.template_reports (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    user_id integer NOT NULL REFERENCES public.users(id),
    public_template_id uuid NOT NULL,
    reason varchar(30) NOT NULL,
    details varchar(1000) NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, user_id, public_template_id, reason)
);

CREATE TABLE public.template_public_stats (
    public_template_id uuid PRIMARY KEY,
    view_count bigint NOT NULL DEFAULT 0,
    like_count bigint NOT NULL DEFAULT 0,
    favorite_count bigint NOT NULL DEFAULT 0,
    usage_count bigint NOT NULL DEFAULT 0,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.outbox_events (
    id uuid PRIMARY KEY,
    aggregate_type varchar(50) NOT NULL,
    aggregate_id varchar(100) NOT NULL,
    event_type varchar(80) NOT NULL,
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    occurred_at timestamptz NOT NULL DEFAULT now(),
    available_at timestamptz NOT NULL DEFAULT now(),
    processed_at timestamptz,
    attempt_count integer NOT NULL DEFAULT 0,
    lease_owner varchar(100),
    lease_until timestamptz,
    last_error_code varchar(50)
);
CREATE INDEX ix_outbox_claim ON public.outbox_events(processed_at,available_at,lease_until) WHERE processed_at IS NULL;

CREATE TABLE public.ai_point_accounts (
    tenant_id uuid PRIMARY KEY REFERENCES public.tenants(id) ON DELETE CASCADE,
    period_start date NOT NULL,
    granted_points bigint NOT NULL DEFAULT 1000 CHECK (granted_points >= 0),
    consumed_points bigint NOT NULL DEFAULT 0 CHECK (consumed_points >= 0),
    held_points bigint NOT NULL DEFAULT 0 CHECK (held_points >= 0),
    version integer NOT NULL DEFAULT 1,
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (consumed_points + held_points <= granted_points)
);

CREATE TABLE public.ai_point_ledger (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    period_start date NOT NULL,
    event_id uuid NOT NULL,
    entry_type varchar(20) NOT NULL CHECK (entry_type IN ('grant','hold','capture','release','adjustment')),
    points bigint NOT NULL CHECK (points > 0),
    reference_type varchar(40) NOT NULL,
    reference_id varchar(100) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, event_id, entry_type)
);

CREATE TABLE public.ai_flash_event_settings (
    id smallint PRIMARY KEY DEFAULT 1 CHECK (id=1),
    timezone varchar(64) NOT NULL,
    open_hour smallint NOT NULL CHECK (open_hour BETWEEN 0 AND 23),
    open_minute smallint NOT NULL CHECK (open_minute BETWEEN 0 AND 59),
    duration_minutes integer NOT NULL CHECK (duration_minutes>0),
    total_slots integer NOT NULL CHECK (total_slots>0),
    points_cost integer NOT NULL CHECK (points_cost>0),
    required_streak_days integer NOT NULL CHECK (required_streak_days>0),
    monthly_grant_points integer NOT NULL CHECK (monthly_grant_points>0),
    enabled boolean NOT NULL DEFAULT true,
    updated_at timestamptz NOT NULL DEFAULT now()
);
INSERT INTO public.ai_flash_event_settings(id,timezone,open_hour,open_minute,duration_minutes,total_slots,points_cost,required_streak_days,monthly_grant_points)
VALUES(1,'Asia/Shanghai',20,0,10,10,100,5,1000);

CREATE TABLE public.ai_flash_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id uuid NOT NULL UNIQUE,
    event_date date NOT NULL,
    timezone varchar(64) NOT NULL DEFAULT 'Asia/Shanghai',
    opens_at timestamptz NOT NULL,
    closes_at timestamptz NOT NULL,
    total_slots integer NOT NULL DEFAULT 10 CHECK (total_slots > 0),
    claimed_slots integer NOT NULL DEFAULT 0 CHECK (claimed_slots >= 0 AND claimed_slots <= total_slots),
    points_cost integer NOT NULL DEFAULT 100 CHECK (points_cost > 0),
    required_streak_days integer NOT NULL DEFAULT 5 CHECK (required_streak_days > 0),
    status varchar(20) NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled','open','closed','paused','cancelled')),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (event_date, timezone),
    CHECK (closes_at > opens_at)
);

CREATE TABLE public.ai_flash_claims (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id bigint NOT NULL REFERENCES public.ai_flash_events(id),
    tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    user_id integer NOT NULL REFERENCES public.users(id),
    request_id uuid NOT NULL,
    status varchar(20) NOT NULL CHECK (status IN ('queued','running','succeeded','failed')),
    points_cost integer NOT NULL,
    streak_days_at_claim integer NOT NULL,
    claimed_at timestamptz NOT NULL DEFAULT now(),
    finished_at timestamptz,
    report_note_id integer REFERENCES public.notes(id),
    error_code varchar(50),
    UNIQUE (event_id, tenant_id),
    UNIQUE (tenant_id, request_id)
);

CREATE TABLE public.ai_event_jobs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id bigint NOT NULL UNIQUE REFERENCES public.ai_flash_claims(id) ON DELETE CASCADE,
    status varchar(20) NOT NULL DEFAULT 'queued' CHECK (status IN ('queued','running','success','failed')),
    attempt_count integer NOT NULL DEFAULT 0,
    max_attempts integer NOT NULL DEFAULT 3,
    available_at timestamptz NOT NULL DEFAULT now(),
    lease_owner varchar(100),
    lease_until timestamptz,
    last_error_code varchar(50),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_ai_event_jobs_claim ON public.ai_event_jobs(status, available_at, lease_until, id);

CREATE TABLE public.tenant_daily_writing_stats (
    tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    local_date date NOT NULL,
    timezone varchar(64) NOT NULL,
    eligible_note_count integer NOT NULL,
    eligible_word_count bigint NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, local_date, timezone)
);

DO $$
DECLARE table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY['public_profiles','writing_templates','template_publications','template_reactions','template_usages','template_reports','ai_point_accounts','ai_point_ledger','ai_flash_claims','tenant_daily_writing_stats']
  LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', table_name);
    EXECUTE format('ALTER TABLE public.%I FORCE ROW LEVEL SECURITY', table_name);
    EXECUTE format('CREATE POLICY %I ON public.%I USING (tenant_id = NULLIF(current_setting(''app.current_tenant_id'', true), '''')::uuid) WITH CHECK (tenant_id = NULLIF(current_setting(''app.current_tenant_id'', true), '''')::uuid)', table_name || '_tenant_isolation', table_name);
  END LOOP;
END $$;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.public_profiles, public.writing_templates, public.template_publications,
  public.template_reactions, public.template_usages, public.template_reports, public.ai_point_accounts,
  public.ai_point_ledger, public.ai_flash_claims, public.tenant_daily_writing_stats TO diary_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.published_template_snapshots TO diary_app;
GRANT SELECT ON public.template_public_stats TO diary_app;
GRANT SELECT, UPDATE ON public.ai_flash_events TO diary_app;
GRANT SELECT ON public.ai_flash_event_settings TO diary_app;
GRANT INSERT, UPDATE ON public.template_public_stats TO diary_app;
GRANT SELECT, INSERT, UPDATE ON public.ai_event_jobs TO diary_app;
GRANT SELECT, INSERT ON public.outbox_events TO diary_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO diary_app;
