CREATE TABLE public.template_reports (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    user_id integer NOT NULL REFERENCES public.users(id),
    public_template_id uuid NOT NULL,
    reason varchar(30) NOT NULL,
    details varchar(1000) NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now(),
    status varchar(20) NOT NULL DEFAULT 'pending',
    reviewer_id integer REFERENCES public.users(id),
    review_note varchar(1000) NOT NULL DEFAULT '',
    reviewed_at timestamptz,
    CONSTRAINT ck_template_report_status CHECK (status IN ('pending','reviewing','resolved','rejected')),
    UNIQUE (tenant_id, user_id, public_template_id, reason)
);

ALTER TABLE public.template_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.template_reports FORCE ROW LEVEL SECURITY;
CREATE POLICY template_reports_tenant_isolation ON public.template_reports
    USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid);
CREATE INDEX ix_template_reports_review ON public.template_reports(status, created_at, id);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.template_reports TO diary_app;
GRANT USAGE, SELECT ON SEQUENCE public.template_reports_id_seq TO diary_app;
