CREATE TABLE public.recipe_index_jobs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id bigint NOT NULL,
    target_index_version integer NOT NULL CHECK (target_index_version > 0),
    status varchar(20) NOT NULL DEFAULT 'queued'
        CHECK (status IN ('queued', 'running', 'success', 'failed', 'cancelled')),
    lease_owner varchar(120),
    lease_until timestamptz,
    attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    next_attempt_at timestamptz NOT NULL DEFAULT now(),
    last_error_code varchar(80),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT recipe_index_jobs_document_fk
        FOREIGN KEY (document_id) REFERENCES public.recipe_documents(id) ON DELETE CASCADE,
    CONSTRAINT recipe_index_jobs_document_version_unique
        UNIQUE (document_id, target_index_version)
);

CREATE INDEX ix_recipe_index_jobs_claim
    ON public.recipe_index_jobs (status, next_attempt_at, lease_until, id)
    WHERE status IN ('queued', 'running');
CREATE INDEX ix_recipe_index_jobs_document
    ON public.recipe_index_jobs (document_id, updated_at DESC);
