CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;

ALTER TABLE public.tenants
    ADD COLUMN knowledge_quota_bytes bigint NOT NULL DEFAULT 1073741824
        CHECK (knowledge_quota_bytes > 0);

CREATE TABLE public.knowledge_collections (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by integer NOT NULL,
    name varchar(120) NOT NULL,
    description varchar(500),
    version integer NOT NULL DEFAULT 1 CHECK (version > 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    UNIQUE (tenant_id, id),
    FOREIGN KEY (tenant_id, created_by) REFERENCES public.tenants(id, user_id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX uq_knowledge_collections_active_name
    ON public.knowledge_collections (tenant_id, lower(name))
    WHERE deleted_at IS NULL;
CREATE INDEX ix_knowledge_collections_tenant
    ON public.knowledge_collections (tenant_id, updated_at DESC);

CREATE TABLE public.knowledge_documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id uuid NOT NULL,
    uploaded_by integer NOT NULL,
    collection_id bigint,
    original_name varchar(255) NOT NULL,
    stored_path varchar(500) NOT NULL,
    mime_type varchar(120) NOT NULL,
    extension varchar(10) NOT NULL CHECK (extension IN ('.txt', '.pdf', '.docx')),
    size bigint NOT NULL CHECK (size > 0),
    sha256 char(64) NOT NULL,
    status varchar(30) NOT NULL DEFAULT 'uploaded'
        CHECK (status IN ('uploaded', 'extracting', 'indexing', 'ready', 'failed', 'deleting')),
    page_count integer CHECK (page_count IS NULL OR page_count >= 0),
    character_count bigint NOT NULL DEFAULT 0 CHECK (character_count >= 0),
    parent_chunk_count integer NOT NULL DEFAULT 0 CHECK (parent_chunk_count >= 0),
    child_chunk_count integer NOT NULL DEFAULT 0 CHECK (child_chunk_count >= 0),
    language varchar(32),
    error_code varchar(80),
    error_message varchar(500),
    index_version integer NOT NULL DEFAULT 1 CHECK (index_version > 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    UNIQUE (tenant_id, id),
    UNIQUE (tenant_id, stored_path),
    FOREIGN KEY (tenant_id, uploaded_by) REFERENCES public.tenants(id, user_id) ON DELETE CASCADE,
    FOREIGN KEY (tenant_id, collection_id) REFERENCES public.knowledge_collections(tenant_id, id)
);

CREATE UNIQUE INDEX uq_knowledge_documents_active_sha256
    ON public.knowledge_documents (tenant_id, sha256)
    WHERE deleted_at IS NULL;
CREATE INDEX ix_knowledge_documents_tenant_status
    ON public.knowledge_documents (tenant_id, status, updated_at DESC)
    WHERE deleted_at IS NULL;
CREATE INDEX ix_knowledge_documents_collection
    ON public.knowledge_documents (tenant_id, collection_id, updated_at DESC)
    WHERE deleted_at IS NULL;

CREATE TABLE public.knowledge_parent_chunks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id uuid NOT NULL,
    document_id bigint NOT NULL,
    index_version integer NOT NULL CHECK (index_version > 0),
    parent_index integer NOT NULL CHECK (parent_index >= 0),
    page_from integer,
    page_to integer,
    heading_path text,
    content text NOT NULL,
    content_hash char(64) NOT NULL,
    token_count integer NOT NULL DEFAULT 0 CHECK (token_count >= 0),
    previous_parent_id bigint,
    next_parent_id bigint,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, id),
    UNIQUE (tenant_id, document_id, index_version, parent_index),
    FOREIGN KEY (tenant_id, document_id) REFERENCES public.knowledge_documents(tenant_id, id) ON DELETE CASCADE,
    FOREIGN KEY (tenant_id, previous_parent_id) REFERENCES public.knowledge_parent_chunks(tenant_id, id),
    FOREIGN KEY (tenant_id, next_parent_id) REFERENCES public.knowledge_parent_chunks(tenant_id, id),
    CHECK (page_from IS NULL OR page_from > 0),
    CHECK (page_to IS NULL OR page_to >= page_from)
);

CREATE INDEX ix_knowledge_parent_chunks_document
    ON public.knowledge_parent_chunks (tenant_id, document_id, index_version, parent_index);

CREATE TABLE public.knowledge_child_chunks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id uuid NOT NULL,
    document_id bigint NOT NULL,
    parent_id bigint NOT NULL,
    index_version integer NOT NULL CHECK (index_version > 0),
    child_index integer NOT NULL CHECK (child_index >= 0),
    page_from integer,
    page_to integer,
    heading_path text,
    content text NOT NULL,
    embedding_text text NOT NULL,
    content_hash char(64) NOT NULL,
    search_vector tsvector NOT NULL,
    embedding public.vector(1024),
    embedding_model varchar(120),
    token_count integer NOT NULL DEFAULT 0 CHECK (token_count >= 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, id),
    UNIQUE (tenant_id, parent_id, child_index),
    FOREIGN KEY (tenant_id, document_id) REFERENCES public.knowledge_documents(tenant_id, id) ON DELETE CASCADE,
    FOREIGN KEY (tenant_id, parent_id) REFERENCES public.knowledge_parent_chunks(tenant_id, id) ON DELETE CASCADE,
    CHECK (page_from IS NULL OR page_from > 0),
    CHECK (page_to IS NULL OR page_to >= page_from),
    CHECK ((embedding IS NULL) = (embedding_model IS NULL))
);

CREATE INDEX ix_knowledge_child_chunks_document
    ON public.knowledge_child_chunks (tenant_id, document_id, index_version, child_index);
CREATE INDEX ix_knowledge_child_chunks_search
    ON public.knowledge_child_chunks USING gin (search_vector);

CREATE TABLE public.knowledge_index_jobs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id uuid NOT NULL,
    document_id bigint NOT NULL,
    target_index_version integer NOT NULL CHECK (target_index_version > 0),
    status varchar(20) NOT NULL DEFAULT 'queued'
        CHECK (status IN ('queued', 'running', 'success', 'failed', 'cancelled')),
    lease_owner varchar(120),
    lease_until timestamptz,
    attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    next_attempt_at timestamptz NOT NULL DEFAULT now(),
    last_error_code varchar(80),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, document_id, target_index_version),
    FOREIGN KEY (tenant_id, document_id) REFERENCES public.knowledge_documents(tenant_id, id) ON DELETE CASCADE
);

CREATE INDEX ix_knowledge_index_jobs_claim
    ON public.knowledge_index_jobs (status, next_attempt_at, lease_until, id)
    WHERE status IN ('queued', 'running');
CREATE INDEX ix_knowledge_index_jobs_tenant
    ON public.knowledge_index_jobs (tenant_id, document_id, updated_at DESC);

CREATE TABLE public.knowledge_message_sources (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id uuid NOT NULL,
    message_id integer NOT NULL,
    document_id bigint NOT NULL,
    parent_id bigint,
    child_id bigint,
    index_version integer NOT NULL CHECK (index_version > 0),
    snippet text,
    page_from integer,
    page_to integer,
    score numeric(10, 8) NOT NULL DEFAULT 0,
    rank integer NOT NULL CHECK (rank > 0),
    source_deleted boolean NOT NULL DEFAULT false,
    UNIQUE (tenant_id, message_id, rank),
    FOREIGN KEY (tenant_id, document_id) REFERENCES public.knowledge_documents(tenant_id, id),
    FOREIGN KEY (tenant_id, parent_id) REFERENCES public.knowledge_parent_chunks(tenant_id, id),
    FOREIGN KEY (tenant_id, child_id) REFERENCES public.knowledge_child_chunks(tenant_id, id),
    FOREIGN KEY (tenant_id, message_id) REFERENCES public.messages(tenant_id, id) ON DELETE CASCADE
);

CREATE INDEX ix_knowledge_message_sources_message
    ON public.knowledge_message_sources (tenant_id, message_id, rank);

ALTER TABLE public.conversations
    ADD COLUMN source_scope varchar(20) NOT NULL DEFAULT 'growth'
        CHECK (source_scope IN ('knowledge', 'growth', 'all'));
ALTER TABLE public.messages
    ADD COLUMN status varchar(20) NOT NULL DEFAULT 'complete'
        CHECK (status IN ('pending', 'complete', 'failed', 'cancelled')),
    ADD COLUMN request_id varchar(128);
CREATE UNIQUE INDEX uq_messages_tenant_request
    ON public.messages (tenant_id, request_id)
    WHERE request_id IS NOT NULL;

ALTER TABLE public.knowledge_collections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.knowledge_collections FORCE ROW LEVEL SECURITY;
CREATE POLICY knowledge_collections_tenant_isolation ON public.knowledge_collections
    USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid);

ALTER TABLE public.knowledge_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.knowledge_documents FORCE ROW LEVEL SECURITY;
CREATE POLICY knowledge_documents_tenant_isolation ON public.knowledge_documents
    USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid);

ALTER TABLE public.knowledge_parent_chunks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.knowledge_parent_chunks FORCE ROW LEVEL SECURITY;
CREATE POLICY knowledge_parent_chunks_tenant_isolation ON public.knowledge_parent_chunks
    USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid);

ALTER TABLE public.knowledge_child_chunks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.knowledge_child_chunks FORCE ROW LEVEL SECURITY;
CREATE POLICY knowledge_child_chunks_tenant_isolation ON public.knowledge_child_chunks
    USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid);

ALTER TABLE public.knowledge_index_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.knowledge_index_jobs FORCE ROW LEVEL SECURITY;
CREATE POLICY knowledge_index_jobs_tenant_isolation ON public.knowledge_index_jobs
    USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid);

ALTER TABLE public.knowledge_message_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.knowledge_message_sources FORCE ROW LEVEL SECURITY;
CREATE POLICY knowledge_message_sources_tenant_isolation ON public.knowledge_message_sources
    USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.knowledge_collections TO diary_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.knowledge_documents TO diary_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.knowledge_parent_chunks TO diary_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.knowledge_child_chunks TO diary_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.knowledge_index_jobs TO diary_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.knowledge_message_sources TO diary_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO diary_app;
