ALTER TABLE public.conversations
  ADD COLUMN version integer NOT NULL DEFAULT 1,
  ADD COLUMN summary text,
  ADD COLUMN summary_through_message_id integer,
  ADD COLUMN summary_version integer NOT NULL DEFAULT 0,
  ADD COLUMN summary_model varchar(120),
  ADD COLUMN summary_updated_at timestamptz;

CREATE TABLE public.growth_memories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  category varchar(20) NOT NULL CHECK (category IN ('fact','preference','goal','habit','milestone')),
  content text NOT NULL CHECK (char_length(content) BETWEEN 1 AND 5000),
  importance smallint NOT NULL DEFAULT 5 CHECK (importance BETWEEN 1 AND 10),
  source_type varchar(30) NOT NULL DEFAULT 'manual',
  source_note_id integer,
  source_conversation_id integer,
  source_message_id integer,
  creation_mode varchar(20) NOT NULL DEFAULT 'manual' CHECK (creation_mode IN ('manual','ai_confirmed')),
  version integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  UNIQUE (tenant_id,id),
  FOREIGN KEY (tenant_id,user_id) REFERENCES public.tenants(id,user_id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id,source_note_id) REFERENCES public.notes(tenant_id,id) ON DELETE SET NULL (source_note_id),
  FOREIGN KEY (tenant_id,source_conversation_id) REFERENCES public.conversations(tenant_id,id) ON DELETE SET NULL (source_conversation_id),
  FOREIGN KEY (tenant_id,source_message_id) REFERENCES public.messages(tenant_id,id) ON DELETE SET NULL (source_message_id)
);
ALTER TABLE public.growth_memories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.growth_memories FORCE ROW LEVEL SECURITY;
CREATE POLICY growth_memories_tenant_isolation ON public.growth_memories
  USING (tenant_id=NULLIF(current_setting('app.current_tenant_id',true),'')::uuid)
  WITH CHECK (tenant_id=NULLIF(current_setting('app.current_tenant_id',true),'')::uuid);
CREATE INDEX ix_growth_memories_list ON public.growth_memories(tenant_id,updated_at DESC) WHERE deleted_at IS NULL;
GRANT SELECT,INSERT,UPDATE,DELETE ON public.growth_memories TO diary_app;
GRANT USAGE,SELECT ON SEQUENCE public.growth_memories_id_seq TO diary_app;

CREATE TABLE public.memory_settings (
  tenant_id uuid PRIMARY KEY REFERENCES public.tenants(id) ON DELETE CASCADE,
  user_id integer NOT NULL,
  suggestion_enabled boolean NOT NULL DEFAULT false,
  allowed_categories varchar(20)[] NOT NULL DEFAULT ARRAY['fact','preference','goal','habit','milestone'],
  minimum_importance smallint NOT NULL DEFAULT 5 CHECK (minimum_importance BETWEEN 1 AND 10),
  excluded_note_types varchar(30)[] NOT NULL DEFAULT ARRAY[]::varchar[],
  excluded_tag_ids integer[] NOT NULL DEFAULT ARRAY[]::integer[],
  retention_days integer CHECK (retention_days IS NULL OR retention_days > 0),
  updated_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (tenant_id,user_id) REFERENCES public.tenants(id,user_id) ON DELETE CASCADE
);
ALTER TABLE public.memory_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.memory_settings FORCE ROW LEVEL SECURITY;
CREATE POLICY memory_settings_tenant_isolation ON public.memory_settings
  USING (tenant_id=NULLIF(current_setting('app.current_tenant_id',true),'')::uuid)
  WITH CHECK (tenant_id=NULLIF(current_setting('app.current_tenant_id',true),'')::uuid);
GRANT SELECT,INSERT,UPDATE,DELETE ON public.memory_settings TO diary_app;

CREATE TABLE public.growth_memory_drafts (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  user_id integer NOT NULL,
  items jsonb NOT NULL CHECK (jsonb_typeof(items)='array'),
  status varchar(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','confirmed','rejected','expired')),
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  FOREIGN KEY (tenant_id,user_id) REFERENCES public.tenants(id,user_id) ON DELETE CASCADE
);
ALTER TABLE public.growth_memory_drafts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.growth_memory_drafts FORCE ROW LEVEL SECURITY;
CREATE POLICY growth_memory_drafts_tenant_isolation ON public.growth_memory_drafts
  USING (tenant_id=NULLIF(current_setting('app.current_tenant_id',true),'')::uuid)
  WITH CHECK (tenant_id=NULLIF(current_setting('app.current_tenant_id',true),'')::uuid);
CREATE INDEX ix_growth_memory_drafts_expiry ON public.growth_memory_drafts(tenant_id,expires_at) WHERE status='pending';
GRANT SELECT,INSERT,UPDATE,DELETE ON public.growth_memory_drafts TO diary_app;
