-- Diary Listener PostgreSQL baseline schema.
-- Generated from the accepted Go backend database on 2026-07-26.

--
-- PostgreSQL database dump
--


-- Dumped from database version 16.14
-- Dumped by pg_dump version 16.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: pg_trgm; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;


--
-- Name: EXTENSION pg_trgm; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION pg_trgm IS 'text similarity measurement and index searching based on trigrams';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ai_providers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ai_providers (
    id integer NOT NULL,
    tenant_id uuid NOT NULL,
    display_name character varying(100) NOT NULL,
    base_url character varying(500) NOT NULL,
    default_model character varying(120) NOT NULL,
    capabilities character varying(255) DEFAULT 'chat,stream'::character varying NOT NULL,
    enabled integer DEFAULT 1 NOT NULL
);

ALTER TABLE ONLY public.ai_providers FORCE ROW LEVEL SECURITY;


--
-- Name: ai_providers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ai_providers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_providers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ai_usage_records; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ai_usage_records (
    id integer NOT NULL,
    tenant_id uuid NOT NULL,
    user_id integer NOT NULL,
    request_type character varying(40) NOT NULL,
    input_tokens integer DEFAULT 0 NOT NULL,
    output_tokens integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    model character varying(120),
    duration_ms integer,
    status character varying(30) DEFAULT 'success'::character varying NOT NULL,
    error_code character varying(80)
);

ALTER TABLE ONLY public.ai_usage_records FORCE ROW LEVEL SECURITY;


--
-- Name: ai_usage_records_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ai_usage_records ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_usage_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: attachments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attachments (
    id integer NOT NULL,
    tenant_id uuid NOT NULL,
    uploaded_by integer NOT NULL,
    note_id integer NOT NULL,
    original_name character varying(255) NOT NULL,
    stored_path character varying(500) NOT NULL,
    mime_type character varying(120) NOT NULL,
    size bigint NOT NULL,
    sha256 character varying(64) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY public.attachments FORCE ROW LEVEL SECURITY;


--
-- Name: attachments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.attachments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attachments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audit_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_logs (
    id bigint NOT NULL,
    tenant_id uuid NOT NULL,
    user_id integer NOT NULL,
    action character varying(80) NOT NULL,
    resource_type character varying(40) NOT NULL,
    resource_id character varying(64),
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY public.audit_logs FORCE ROW LEVEL SECURITY;


--
-- Name: audit_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_tokens (
    user_id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    id integer NOT NULL,
    token_hash character varying(64) NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    last_used_at timestamp with time zone
);


--
-- Name: auth_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: conversations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.conversations (
    id integer NOT NULL,
    user_id integer NOT NULL,
    title character varying(255) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    tenant_id uuid NOT NULL
);

ALTER TABLE ONLY public.conversations FORCE ROW LEVEL SECURITY;


--
-- Name: conversations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.conversations_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: conversations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.conversations_id_seq OWNED BY public.conversations.id;


--
-- Name: diary_entries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.diary_entries (
    id integer NOT NULL,
    user_id integer NOT NULL,
    image_path character varying(500),
    content text DEFAULT ''::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    tenant_id uuid NOT NULL
);

ALTER TABLE ONLY public.diary_entries FORCE ROW LEVEL SECURITY;


--
-- Name: diary_entries_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.diary_entries_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: diary_entries_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.diary_entries_id_seq OWNED BY public.diary_entries.id;


--
-- Name: message_sources; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.message_sources (
    id integer NOT NULL,
    tenant_id uuid NOT NULL,
    message_id integer NOT NULL,
    note_id integer NOT NULL,
    snippet text NOT NULL,
    relevance integer DEFAULT 0 NOT NULL,
    rank integer NOT NULL
);

ALTER TABLE ONLY public.message_sources FORCE ROW LEVEL SECURITY;


--
-- Name: message_sources_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.message_sources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.message_sources_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.messages (
    id integer NOT NULL,
    conversation_id integer NOT NULL,
    role character varying(20) NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    tenant_id uuid NOT NULL
);

ALTER TABLE ONLY public.messages FORCE ROW LEVEL SECURITY;


--
-- Name: messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.messages_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: messages_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.messages_id_seq OWNED BY public.messages.id;


--
-- Name: note_revisions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.note_revisions (
    id integer NOT NULL,
    tenant_id uuid NOT NULL,
    note_id integer NOT NULL,
    created_by integer NOT NULL,
    content text NOT NULL,
    reason character varying(40) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY public.note_revisions FORCE ROW LEVEL SECURITY;


--
-- Name: note_revisions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.note_revisions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.note_revisions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: note_tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.note_tags (
    tenant_id uuid NOT NULL,
    note_id integer NOT NULL,
    tag_id integer NOT NULL
);

ALTER TABLE ONLY public.note_tags FORCE ROW LEVEL SECURITY;


--
-- Name: notes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notes (
    id integer NOT NULL,
    tenant_id uuid NOT NULL,
    created_by integer NOT NULL,
    updated_by integer NOT NULL,
    type character varying(20) DEFAULT 'normal'::character varying NOT NULL,
    title character varying(255) NOT NULL,
    content text DEFAULT ''::text NOT NULL,
    note_date date,
    summary text,
    word_count integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    CONSTRAINT ck_notes_type CHECK (((type)::text = ANY ((ARRAY['normal'::character varying, 'daily'::character varying, 'weekly'::character varying, 'monthly'::character varying])::text[])))
);

ALTER TABLE ONLY public.notes FORCE ROW LEVEL SECURITY;


--
-- Name: notes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.notes_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: notes_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.notes_id_seq OWNED BY public.notes.id;


--
-- Name: report_sources; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.report_sources (
    id integer NOT NULL,
    tenant_id uuid NOT NULL,
    report_note_id integer NOT NULL,
    source_note_id integer NOT NULL,
    rank integer NOT NULL
);

ALTER TABLE ONLY public.report_sources FORCE ROW LEVEL SECURITY;


--
-- Name: report_sources_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.report_sources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.report_sources_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: scheduled_report_runs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.scheduled_report_runs (
    id bigint NOT NULL,
    tenant_id uuid NOT NULL,
    task_id integer NOT NULL,
    status character varying(20) NOT NULL,
    trigger character varying(20) NOT NULL,
    report_note_id integer,
    error_code character varying(80),
    error_message text,
    started_at timestamp with time zone NOT NULL,
    finished_at timestamp with time zone
);

ALTER TABLE ONLY public.scheduled_report_runs FORCE ROW LEVEL SECURITY;


--
-- Name: scheduled_report_runs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.scheduled_report_runs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.scheduled_report_runs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: scheduled_report_tasks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.scheduled_report_tasks (
    id integer NOT NULL,
    tenant_id uuid NOT NULL,
    created_by integer NOT NULL,
    report_type character varying(20) NOT NULL,
    hour integer DEFAULT 20 NOT NULL,
    minute integer DEFAULT 0 NOT NULL,
    timezone character varying(64) DEFAULT 'Asia/Shanghai'::character varying NOT NULL,
    status character varying(20) DEFAULT 'enabled'::character varying NOT NULL,
    next_run_at timestamp with time zone NOT NULL,
    last_run_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_scheduled_report_status CHECK (((status)::text = ANY ((ARRAY['enabled'::character varying, 'disabled'::character varying])::text[]))),
    CONSTRAINT ck_scheduled_report_type CHECK (((report_type)::text = ANY ((ARRAY['daily'::character varying, 'weekly'::character varying, 'monthly'::character varying])::text[])))
);

ALTER TABLE ONLY public.scheduled_report_tasks FORCE ROW LEVEL SECURITY;


--
-- Name: scheduled_report_tasks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.scheduled_report_tasks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.scheduled_report_tasks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tags (
    id integer NOT NULL,
    tenant_id uuid NOT NULL,
    name character varying(80) NOT NULL,
    color character varying(20),
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY public.tags FORCE ROW LEVEL SECURITY;


--
-- Name: tags_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tenants; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tenants (
    id uuid NOT NULL,
    user_id integer NOT NULL,
    name character varying(150) NOT NULL,
    status character varying(20) DEFAULT 'active'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    note_quota integer DEFAULT 10000 NOT NULL,
    attachment_quota_bytes bigint DEFAULT '1073741824'::bigint NOT NULL,
    ai_token_quota bigint DEFAULT '1000000'::bigint NOT NULL,
    deleted_at timestamp with time zone
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id integer NOT NULL,
    username character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    password_hash character varying(255) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.users_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;


--
-- Name: conversations id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversations ALTER COLUMN id SET DEFAULT nextval('public.conversations_id_seq'::regclass);


--
-- Name: diary_entries id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.diary_entries ALTER COLUMN id SET DEFAULT nextval('public.diary_entries_id_seq'::regclass);


--
-- Name: messages id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages ALTER COLUMN id SET DEFAULT nextval('public.messages_id_seq'::regclass);


--
-- Name: notes id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notes ALTER COLUMN id SET DEFAULT nextval('public.notes_id_seq'::regclass);


--
-- Name: users id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);


--
-- Name: ai_providers ai_providers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_providers
    ADD CONSTRAINT ai_providers_pkey PRIMARY KEY (id);


--
-- Name: ai_usage_records ai_usage_records_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_usage_records
    ADD CONSTRAINT ai_usage_records_pkey PRIMARY KEY (id);


--
-- Name: attachments attachments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attachments
    ADD CONSTRAINT attachments_pkey PRIMARY KEY (id);


--
-- Name: attachments attachments_stored_path_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attachments
    ADD CONSTRAINT attachments_stored_path_key UNIQUE (stored_path);


--
-- Name: audit_logs audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);


--
-- Name: conversations conversations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT conversations_pkey PRIMARY KEY (id);


--
-- Name: diary_entries diary_entries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.diary_entries
    ADD CONSTRAINT diary_entries_pkey PRIMARY KEY (id);


--
-- Name: message_sources message_sources_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.message_sources
    ADD CONSTRAINT message_sources_pkey PRIMARY KEY (id);


--
-- Name: messages messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_pkey PRIMARY KEY (id);


--
-- Name: note_revisions note_revisions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.note_revisions
    ADD CONSTRAINT note_revisions_pkey PRIMARY KEY (id);


--
-- Name: note_tags note_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.note_tags
    ADD CONSTRAINT note_tags_pkey PRIMARY KEY (tenant_id, note_id, tag_id);


--
-- Name: notes notes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notes
    ADD CONSTRAINT notes_pkey PRIMARY KEY (id);


--
-- Name: auth_tokens pk_auth_tokens; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_tokens
    ADD CONSTRAINT pk_auth_tokens PRIMARY KEY (id);


--
-- Name: report_sources report_sources_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.report_sources
    ADD CONSTRAINT report_sources_pkey PRIMARY KEY (id);


--
-- Name: report_sources report_sources_report_note_id_source_note_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.report_sources
    ADD CONSTRAINT report_sources_report_note_id_source_note_id_key UNIQUE (report_note_id, source_note_id);


--
-- Name: scheduled_report_runs scheduled_report_runs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scheduled_report_runs
    ADD CONSTRAINT scheduled_report_runs_pkey PRIMARY KEY (id);


--
-- Name: scheduled_report_tasks scheduled_report_tasks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scheduled_report_tasks
    ADD CONSTRAINT scheduled_report_tasks_pkey PRIMARY KEY (id);


--
-- Name: tags tags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT tags_pkey PRIMARY KEY (id);


--
-- Name: tenants tenants_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenants
    ADD CONSTRAINT tenants_pkey PRIMARY KEY (id);


--
-- Name: tenants tenants_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenants
    ADD CONSTRAINT tenants_user_id_key UNIQUE (user_id);


--
-- Name: conversations uq_conversations_tenant_id_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT uq_conversations_tenant_id_id UNIQUE (tenant_id, id);


--
-- Name: messages uq_messages_tenant_id_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT uq_messages_tenant_id_id UNIQUE (tenant_id, id);


--
-- Name: notes uq_notes_tenant_id_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notes
    ADD CONSTRAINT uq_notes_tenant_id_id UNIQUE (tenant_id, id);


--
-- Name: tags uq_tags_tenant_id_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT uq_tags_tenant_id_id UNIQUE (tenant_id, id);


--
-- Name: tenants uq_tenants_id_user; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenants
    ADD CONSTRAINT uq_tenants_id_user UNIQUE (id, user_id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: ix_ai_providers_tenant_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_ai_providers_tenant_id ON public.ai_providers USING btree (tenant_id);


--
-- Name: ix_ai_usage_records_tenant_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_ai_usage_records_tenant_id ON public.ai_usage_records USING btree (tenant_id);


--
-- Name: ix_attachments_note_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_attachments_note_id ON public.attachments USING btree (note_id);


--
-- Name: ix_attachments_tenant_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_attachments_tenant_id ON public.attachments USING btree (tenant_id);


--
-- Name: ix_audit_logs_tenant_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_audit_logs_tenant_id ON public.audit_logs USING btree (tenant_id);


--
-- Name: ix_auth_tokens_token_hash; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ix_auth_tokens_token_hash ON public.auth_tokens USING btree (token_hash);


--
-- Name: ix_auth_tokens_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_auth_tokens_user_id ON public.auth_tokens USING btree (user_id);


--
-- Name: ix_conversations_tenant_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_conversations_tenant_id ON public.conversations USING btree (tenant_id);


--
-- Name: ix_diary_entries_tenant_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_diary_entries_tenant_id ON public.diary_entries USING btree (tenant_id);


--
-- Name: ix_message_sources_message_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_message_sources_message_id ON public.message_sources USING btree (message_id);


--
-- Name: ix_message_sources_tenant_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_message_sources_tenant_id ON public.message_sources USING btree (tenant_id);


--
-- Name: ix_messages_tenant_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_messages_tenant_id ON public.messages USING btree (tenant_id);


--
-- Name: ix_note_revisions_note_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_note_revisions_note_id ON public.note_revisions USING btree (note_id);


--
-- Name: ix_note_revisions_tenant_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_note_revisions_tenant_id ON public.note_revisions USING btree (tenant_id);


--
-- Name: ix_notes_content_trgm; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_notes_content_trgm ON public.notes USING gin (content public.gin_trgm_ops);


--
-- Name: ix_notes_tenant_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_notes_tenant_id ON public.notes USING btree (tenant_id);


--
-- Name: ix_notes_title_trgm; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_notes_title_trgm ON public.notes USING gin (title public.gin_trgm_ops);


--
-- Name: ix_report_sources_report_note_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_report_sources_report_note_id ON public.report_sources USING btree (report_note_id);


--
-- Name: ix_report_sources_tenant_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_report_sources_tenant_id ON public.report_sources USING btree (tenant_id);


--
-- Name: ix_scheduled_report_due; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_scheduled_report_due ON public.scheduled_report_tasks USING btree (status, next_run_at);


--
-- Name: ix_scheduled_report_runs_task_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_scheduled_report_runs_task_id ON public.scheduled_report_runs USING btree (task_id);


--
-- Name: ix_scheduled_report_runs_tenant_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_scheduled_report_runs_tenant_id ON public.scheduled_report_runs USING btree (tenant_id);


--
-- Name: ix_scheduled_report_tasks_tenant_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_scheduled_report_tasks_tenant_id ON public.scheduled_report_tasks USING btree (tenant_id);


--
-- Name: ix_tags_tenant_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_tags_tenant_id ON public.tags USING btree (tenant_id);


--
-- Name: uq_notes_tenant_period; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_notes_tenant_period ON public.notes USING btree (tenant_id, type, note_date) WHERE (((type)::text = ANY ((ARRAY['daily'::character varying, 'weekly'::character varying, 'monthly'::character varying])::text[])) AND (deleted_at IS NULL));


--
-- Name: uq_tags_tenant_name; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_tags_tenant_name ON public.tags USING btree (tenant_id, name);


--
-- Name: ai_providers ai_providers_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_providers
    ADD CONSTRAINT ai_providers_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE;


--
-- Name: ai_usage_records ai_usage_records_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_usage_records
    ADD CONSTRAINT ai_usage_records_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE;


--
-- Name: ai_usage_records ai_usage_records_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_usage_records
    ADD CONSTRAINT ai_usage_records_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: attachments attachments_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attachments
    ADD CONSTRAINT attachments_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE;


--
-- Name: attachments attachments_tenant_id_note_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attachments
    ADD CONSTRAINT attachments_tenant_id_note_id_fkey FOREIGN KEY (tenant_id, note_id) REFERENCES public.notes(tenant_id, id) ON DELETE CASCADE;


--
-- Name: attachments attachments_tenant_id_uploaded_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attachments
    ADD CONSTRAINT attachments_tenant_id_uploaded_by_fkey FOREIGN KEY (tenant_id, uploaded_by) REFERENCES public.tenants(id, user_id) ON DELETE CASCADE;


--
-- Name: attachments attachments_uploaded_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attachments
    ADD CONSTRAINT attachments_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.users(id);


--
-- Name: audit_logs audit_logs_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE;


--
-- Name: audit_logs audit_logs_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: auth_tokens auth_tokens_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_tokens
    ADD CONSTRAINT auth_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: conversations conversations_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT conversations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: diary_entries diary_entries_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.diary_entries
    ADD CONSTRAINT diary_entries_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: ai_usage_records fk_ai_usage_tenant_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_usage_records
    ADD CONSTRAINT fk_ai_usage_tenant_user FOREIGN KEY (tenant_id, user_id) REFERENCES public.tenants(id, user_id) ON DELETE CASCADE;


--
-- Name: audit_logs fk_audit_tenant_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT fk_audit_tenant_user FOREIGN KEY (tenant_id, user_id) REFERENCES public.tenants(id, user_id) ON DELETE CASCADE;


--
-- Name: conversations fk_conversations_tenant; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT fk_conversations_tenant FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE;


--
-- Name: conversations fk_conversations_tenant_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT fk_conversations_tenant_user FOREIGN KEY (tenant_id, user_id) REFERENCES public.tenants(id, user_id) ON DELETE CASCADE;


--
-- Name: diary_entries fk_diary_entries_tenant; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.diary_entries
    ADD CONSTRAINT fk_diary_entries_tenant FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE;


--
-- Name: diary_entries fk_diary_entries_tenant_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.diary_entries
    ADD CONSTRAINT fk_diary_entries_tenant_user FOREIGN KEY (tenant_id, user_id) REFERENCES public.tenants(id, user_id) ON DELETE CASCADE;


--
-- Name: messages fk_messages_tenant; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT fk_messages_tenant FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE;


--
-- Name: messages fk_messages_tenant_conversation; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT fk_messages_tenant_conversation FOREIGN KEY (tenant_id, conversation_id) REFERENCES public.conversations(tenant_id, id) ON DELETE CASCADE;


--
-- Name: notes fk_notes_tenant_creator; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notes
    ADD CONSTRAINT fk_notes_tenant_creator FOREIGN KEY (tenant_id, created_by) REFERENCES public.tenants(id, user_id) ON DELETE CASCADE;


--
-- Name: notes fk_notes_tenant_updater; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notes
    ADD CONSTRAINT fk_notes_tenant_updater FOREIGN KEY (tenant_id, updated_by) REFERENCES public.tenants(id, user_id) ON DELETE CASCADE;


--
-- Name: note_revisions fk_revisions_tenant_note; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.note_revisions
    ADD CONSTRAINT fk_revisions_tenant_note FOREIGN KEY (tenant_id, note_id) REFERENCES public.notes(tenant_id, id) ON DELETE CASCADE;


--
-- Name: note_revisions fk_revisions_tenant_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.note_revisions
    ADD CONSTRAINT fk_revisions_tenant_user FOREIGN KEY (tenant_id, created_by) REFERENCES public.tenants(id, user_id) ON DELETE CASCADE;


--
-- Name: message_sources message_sources_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.message_sources
    ADD CONSTRAINT message_sources_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE;


--
-- Name: message_sources message_sources_tenant_id_message_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.message_sources
    ADD CONSTRAINT message_sources_tenant_id_message_id_fkey FOREIGN KEY (tenant_id, message_id) REFERENCES public.messages(tenant_id, id) ON DELETE CASCADE;


--
-- Name: message_sources message_sources_tenant_id_note_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.message_sources
    ADD CONSTRAINT message_sources_tenant_id_note_id_fkey FOREIGN KEY (tenant_id, note_id) REFERENCES public.notes(tenant_id, id) ON DELETE CASCADE;


--
-- Name: messages messages_conversation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id) ON DELETE CASCADE;


--
-- Name: note_revisions note_revisions_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.note_revisions
    ADD CONSTRAINT note_revisions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: note_revisions note_revisions_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.note_revisions
    ADD CONSTRAINT note_revisions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE;


--
-- Name: note_tags note_tags_tenant_id_note_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.note_tags
    ADD CONSTRAINT note_tags_tenant_id_note_id_fkey FOREIGN KEY (tenant_id, note_id) REFERENCES public.notes(tenant_id, id) ON DELETE CASCADE;


--
-- Name: note_tags note_tags_tenant_id_tag_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.note_tags
    ADD CONSTRAINT note_tags_tenant_id_tag_id_fkey FOREIGN KEY (tenant_id, tag_id) REFERENCES public.tags(tenant_id, id) ON DELETE CASCADE;


--
-- Name: notes notes_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notes
    ADD CONSTRAINT notes_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: notes notes_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notes
    ADD CONSTRAINT notes_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE;


--
-- Name: notes notes_updated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notes
    ADD CONSTRAINT notes_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id);


--
-- Name: report_sources report_sources_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.report_sources
    ADD CONSTRAINT report_sources_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE;


--
-- Name: report_sources report_sources_tenant_id_report_note_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.report_sources
    ADD CONSTRAINT report_sources_tenant_id_report_note_id_fkey FOREIGN KEY (tenant_id, report_note_id) REFERENCES public.notes(tenant_id, id) ON DELETE CASCADE;


--
-- Name: report_sources report_sources_tenant_id_source_note_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.report_sources
    ADD CONSTRAINT report_sources_tenant_id_source_note_id_fkey FOREIGN KEY (tenant_id, source_note_id) REFERENCES public.notes(tenant_id, id) ON DELETE CASCADE;


--
-- Name: scheduled_report_runs scheduled_report_runs_report_note_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scheduled_report_runs
    ADD CONSTRAINT scheduled_report_runs_report_note_id_fkey FOREIGN KEY (report_note_id) REFERENCES public.notes(id) ON DELETE SET NULL;


--
-- Name: scheduled_report_runs scheduled_report_runs_task_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scheduled_report_runs
    ADD CONSTRAINT scheduled_report_runs_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.scheduled_report_tasks(id) ON DELETE CASCADE;


--
-- Name: scheduled_report_runs scheduled_report_runs_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scheduled_report_runs
    ADD CONSTRAINT scheduled_report_runs_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE;


--
-- Name: scheduled_report_tasks scheduled_report_tasks_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scheduled_report_tasks
    ADD CONSTRAINT scheduled_report_tasks_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: scheduled_report_tasks scheduled_report_tasks_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scheduled_report_tasks
    ADD CONSTRAINT scheduled_report_tasks_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE;


--
-- Name: tags tags_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT tags_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE;


--
-- Name: tenants tenants_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenants
    ADD CONSTRAINT tenants_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: ai_providers; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.ai_providers ENABLE ROW LEVEL SECURITY;

--
-- Name: ai_providers ai_providers_tenant_isolation; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY ai_providers_tenant_isolation ON public.ai_providers USING ((tenant_id = (NULLIF(current_setting('app.current_tenant_id'::text, true), ''::text))::uuid)) WITH CHECK ((tenant_id = (NULLIF(current_setting('app.current_tenant_id'::text, true), ''::text))::uuid));


--
-- Name: ai_usage_records; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.ai_usage_records ENABLE ROW LEVEL SECURITY;

--
-- Name: ai_usage_records ai_usage_records_tenant_isolation; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY ai_usage_records_tenant_isolation ON public.ai_usage_records USING ((tenant_id = (NULLIF(current_setting('app.current_tenant_id'::text, true), ''::text))::uuid)) WITH CHECK ((tenant_id = (NULLIF(current_setting('app.current_tenant_id'::text, true), ''::text))::uuid));


--
-- Name: attachments; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.attachments ENABLE ROW LEVEL SECURITY;

--
-- Name: attachments attachments_tenant_isolation; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY attachments_tenant_isolation ON public.attachments USING ((tenant_id = (NULLIF(current_setting('app.current_tenant_id'::text, true), ''::text))::uuid)) WITH CHECK ((tenant_id = (NULLIF(current_setting('app.current_tenant_id'::text, true), ''::text))::uuid));


--
-- Name: audit_logs; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

--
-- Name: audit_logs audit_logs_tenant_isolation; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY audit_logs_tenant_isolation ON public.audit_logs USING ((tenant_id = (NULLIF(current_setting('app.current_tenant_id'::text, true), ''::text))::uuid)) WITH CHECK ((tenant_id = (NULLIF(current_setting('app.current_tenant_id'::text, true), ''::text))::uuid));


--
-- Name: conversations; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;

--
-- Name: conversations conversations_tenant_isolation; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY conversations_tenant_isolation ON public.conversations USING ((tenant_id = (NULLIF(current_setting('app.current_tenant_id'::text, true), ''::text))::uuid)) WITH CHECK ((tenant_id = (NULLIF(current_setting('app.current_tenant_id'::text, true), ''::text))::uuid));


--
-- Name: diary_entries; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.diary_entries ENABLE ROW LEVEL SECURITY;

--
-- Name: diary_entries diary_entries_tenant_isolation; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY diary_entries_tenant_isolation ON public.diary_entries USING ((tenant_id = (NULLIF(current_setting('app.current_tenant_id'::text, true), ''::text))::uuid)) WITH CHECK ((tenant_id = (NULLIF(current_setting('app.current_tenant_id'::text, true), ''::text))::uuid));


--
-- Name: message_sources; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.message_sources ENABLE ROW LEVEL SECURITY;

--
-- Name: message_sources message_sources_tenant_isolation; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY message_sources_tenant_isolation ON public.message_sources USING ((tenant_id = (NULLIF(current_setting('app.current_tenant_id'::text, true), ''::text))::uuid)) WITH CHECK ((tenant_id = (NULLIF(current_setting('app.current_tenant_id'::text, true), ''::text))::uuid));


--
-- Name: messages; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

--
-- Name: messages messages_tenant_isolation; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY messages_tenant_isolation ON public.messages USING ((tenant_id = (NULLIF(current_setting('app.current_tenant_id'::text, true), ''::text))::uuid)) WITH CHECK ((tenant_id = (NULLIF(current_setting('app.current_tenant_id'::text, true), ''::text))::uuid));


--
-- Name: note_revisions; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.note_revisions ENABLE ROW LEVEL SECURITY;

--
-- Name: note_revisions note_revisions_tenant_isolation; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY note_revisions_tenant_isolation ON public.note_revisions USING ((tenant_id = (NULLIF(current_setting('app.current_tenant_id'::text, true), ''::text))::uuid)) WITH CHECK ((tenant_id = (NULLIF(current_setting('app.current_tenant_id'::text, true), ''::text))::uuid));


--
-- Name: note_tags; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.note_tags ENABLE ROW LEVEL SECURITY;

--
-- Name: note_tags note_tags_tenant_isolation; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY note_tags_tenant_isolation ON public.note_tags USING ((tenant_id = (NULLIF(current_setting('app.current_tenant_id'::text, true), ''::text))::uuid)) WITH CHECK ((tenant_id = (NULLIF(current_setting('app.current_tenant_id'::text, true), ''::text))::uuid));


--
-- Name: notes; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.notes ENABLE ROW LEVEL SECURITY;

--
-- Name: notes notes_tenant_isolation; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY notes_tenant_isolation ON public.notes USING ((tenant_id = (NULLIF(current_setting('app.current_tenant_id'::text, true), ''::text))::uuid)) WITH CHECK ((tenant_id = (NULLIF(current_setting('app.current_tenant_id'::text, true), ''::text))::uuid));


--
-- Name: report_sources; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.report_sources ENABLE ROW LEVEL SECURITY;

--
-- Name: report_sources report_sources_tenant_isolation; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY report_sources_tenant_isolation ON public.report_sources USING ((tenant_id = (NULLIF(current_setting('app.current_tenant_id'::text, true), ''::text))::uuid)) WITH CHECK ((tenant_id = (NULLIF(current_setting('app.current_tenant_id'::text, true), ''::text))::uuid));


--
-- Name: scheduled_report_runs; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.scheduled_report_runs ENABLE ROW LEVEL SECURITY;

--
-- Name: scheduled_report_runs scheduled_report_runs_tenant_isolation; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY scheduled_report_runs_tenant_isolation ON public.scheduled_report_runs USING ((tenant_id = (NULLIF(current_setting('app.current_tenant_id'::text, true), ''::text))::uuid)) WITH CHECK ((tenant_id = (NULLIF(current_setting('app.current_tenant_id'::text, true), ''::text))::uuid));


--
-- Name: scheduled_report_tasks; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.scheduled_report_tasks ENABLE ROW LEVEL SECURITY;

--
-- Name: scheduled_report_tasks scheduled_report_tasks_tenant_isolation; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY scheduled_report_tasks_tenant_isolation ON public.scheduled_report_tasks USING ((tenant_id = (NULLIF(current_setting('app.current_tenant_id'::text, true), ''::text))::uuid)) WITH CHECK ((tenant_id = (NULLIF(current_setting('app.current_tenant_id'::text, true), ''::text))::uuid));


--
-- Name: tags; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.tags ENABLE ROW LEVEL SECURITY;

--
-- Name: tags tags_tenant_isolation; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tags_tenant_isolation ON public.tags USING ((tenant_id = (NULLIF(current_setting('app.current_tenant_id'::text, true), ''::text))::uuid)) WITH CHECK ((tenant_id = (NULLIF(current_setting('app.current_tenant_id'::text, true), ''::text))::uuid));


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: -
--

GRANT USAGE ON SCHEMA public TO diary_app;


--
-- Name: TABLE ai_providers; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.ai_providers TO diary_app;


--
-- Name: SEQUENCE ai_providers_id_seq; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,USAGE ON SEQUENCE public.ai_providers_id_seq TO diary_app;


--
-- Name: TABLE ai_usage_records; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.ai_usage_records TO diary_app;


--
-- Name: SEQUENCE ai_usage_records_id_seq; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,USAGE ON SEQUENCE public.ai_usage_records_id_seq TO diary_app;


--
-- Name: TABLE attachments; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.attachments TO diary_app;


--
-- Name: SEQUENCE attachments_id_seq; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,USAGE ON SEQUENCE public.attachments_id_seq TO diary_app;


--
-- Name: TABLE audit_logs; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.audit_logs TO diary_app;


--
-- Name: SEQUENCE audit_logs_id_seq; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,USAGE ON SEQUENCE public.audit_logs_id_seq TO diary_app;


--
-- Name: TABLE auth_tokens; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.auth_tokens TO diary_app;


--
-- Name: SEQUENCE auth_tokens_id_seq; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,USAGE ON SEQUENCE public.auth_tokens_id_seq TO diary_app;


--
-- Name: TABLE conversations; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.conversations TO diary_app;


--
-- Name: SEQUENCE conversations_id_seq; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,USAGE ON SEQUENCE public.conversations_id_seq TO diary_app;


--
-- Name: TABLE diary_entries; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.diary_entries TO diary_app;


--
-- Name: SEQUENCE diary_entries_id_seq; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,USAGE ON SEQUENCE public.diary_entries_id_seq TO diary_app;


--
-- Name: TABLE message_sources; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.message_sources TO diary_app;


--
-- Name: SEQUENCE message_sources_id_seq; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,USAGE ON SEQUENCE public.message_sources_id_seq TO diary_app;


--
-- Name: TABLE messages; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.messages TO diary_app;


--
-- Name: SEQUENCE messages_id_seq; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,USAGE ON SEQUENCE public.messages_id_seq TO diary_app;


--
-- Name: TABLE note_revisions; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.note_revisions TO diary_app;


--
-- Name: SEQUENCE note_revisions_id_seq; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,USAGE ON SEQUENCE public.note_revisions_id_seq TO diary_app;


--
-- Name: TABLE note_tags; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.note_tags TO diary_app;


--
-- Name: TABLE notes; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.notes TO diary_app;


--
-- Name: SEQUENCE notes_id_seq; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,USAGE ON SEQUENCE public.notes_id_seq TO diary_app;


--
-- Name: TABLE report_sources; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.report_sources TO diary_app;


--
-- Name: SEQUENCE report_sources_id_seq; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,USAGE ON SEQUENCE public.report_sources_id_seq TO diary_app;


--
-- Name: TABLE scheduled_report_runs; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.scheduled_report_runs TO diary_app;


--
-- Name: SEQUENCE scheduled_report_runs_id_seq; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,USAGE ON SEQUENCE public.scheduled_report_runs_id_seq TO diary_app;


--
-- Name: TABLE scheduled_report_tasks; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.scheduled_report_tasks TO diary_app;


--
-- Name: SEQUENCE scheduled_report_tasks_id_seq; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,USAGE ON SEQUENCE public.scheduled_report_tasks_id_seq TO diary_app;


--
-- Name: TABLE tags; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.tags TO diary_app;


--
-- Name: SEQUENCE tags_id_seq; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,USAGE ON SEQUENCE public.tags_id_seq TO diary_app;


--
-- Name: TABLE tenants; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.tenants TO diary_app;


--
-- Name: TABLE users; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.users TO diary_app;


--
-- Name: SEQUENCE users_id_seq; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,USAGE ON SEQUENCE public.users_id_seq TO diary_app;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: -
--

ALTER DEFAULT PRIVILEGES FOR ROLE diary_migrator IN SCHEMA public GRANT SELECT,USAGE ON SEQUENCES TO diary_app;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: -
--

ALTER DEFAULT PRIVILEGES FOR ROLE diary_migrator IN SCHEMA public GRANT SELECT,INSERT,DELETE,UPDATE ON TABLES TO diary_app;


--
-- PostgreSQL database dump complete
--
