apiVersion: v1
kind: Service
metadata:
  name: {{ include "diary-listener.name" . }}-frontend
spec:
  selector:
    app.kubernetes.io/name: {{ include "diary-listener.name" . }}-frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - {name: http, port: {{ .Values.frontend.port }}, targetPort: http}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "diary-listener.name" . }}-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "diary-listener.name" . }}-frontend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "diary-listener.name" . }}-frontend
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - {name: http, containerPort: {{ .Values.frontend.port }}}
          readinessProbe:
            httpGet: {path: /, port: http}
